name: update race data
run-name: pull results and reorganize data for our platform
on: [push]
jobs:
  Update-Race-Data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Download latest data
        uses: sozo-design/curl@v1.0.2
        with:
          args: -o statistics.html https://f1fantasytools.com/statistics
      - name: Process latest data
        run: |
          cat statistics.html | python3 stats_to_race_data.py > race_data.js      
      - name: GIT add the potentially updated file
        run: |
          git add race_data.js
      - name: GIT commit
        run: |
          git commit -m "race data updated by github action"
      - name: GIT push
        run: |
          git push
