name: update race data
run-name: pull results and reorganize data for our platform
on: [push]
jobs:
  Update-Race-Data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Download latest data
        uses: sozo-design/curl@v1.0.2
        with:
          args: -o statistics.html https://f1fantasytools.com/statistics
      - name: Process latest data
        run: |
          cat statistics.html | python3 stats_to_race_data.py > new_race_data.js      
      - name: List files in the repository
        run: |
          ls -la ${{ github.workspace }}
      - name: Compute checksum of old file
        run: |
          md5sum race_data.js
      - name: Compute checksum of new file
        run: |
          md5sum new_race_data.js
